// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzemlccctubxvthjlmpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6ZW1sY2NjdHVieHZ0aGpsbXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjExNDksImV4cCI6MjA2MzU5NzE0OX0.wNfV_V6I_emUo5cX1fDjIiz-NXnbo80_YOOU6z3wYWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);